### ISSUE TITLE
Error on flinkhose deploy

### ISSUE THREAD

**Issue by liquidweavergit** [DemandCube/flinkhose#40] opened 2017-01-04 23:11 UTC
This was after removing from flinkhose_config.yml:
role_name: test-one-execution-role

Aborting.
[localhost] local: zappa deploy
Calling deploy for environment dev..
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/private/var/folders/_0/8tm7550n58vgzxw9l7yq0zk00000gn/T/tmpZbl5PS/lib/python2.7/site-packages/zappa/cli.py", line 1847, in handle
    sys.exit(cli.handle())
  File "/private/var/folders/_0/8tm7550n58vgzxw9l7yq0zk00000gn/T/tmpZbl5PS/lib/python2.7/site-packages/zappa/cli.py", line 345, in handle
    self.dispatch_command(self.command, environment)
  File "/private/var/folders/_0/8tm7550n58vgzxw9l7yq0zk00000gn/T/tmpZbl5PS/lib/python2.7/site-packages/zappa/cli.py", line 377, in dispatch_command
    self.deploy()
  File "/private/var/folders/_0/8tm7550n58vgzxw9l7yq0zk00000gn/T/tmpZbl5PS/lib/python2.7/site-packages/zappa/cli.py", line 445, in deploy
    self.zappa.create_iam_roles()
  File "/private/var/folders/_0/8tm7550n58vgzxw9l7yq0zk00000gn/T/tmpZbl5PS/lib/python2.7/site-packages/zappa/zappa.py", line 1524, in create_iam_roles
    role, credentials_arn = self.get_credentials_arn()
  File "/private/var/folders/_0/8tm7550n58vgzxw9l7yq0zk00000gn/T/tmpZbl5PS/lib/python2.7/site-packages/zappa/zappa.py", line 1508, in get_credentials_arn
    role = self.iam.Role(self.role_name)
  File "/private/var/folders/_0/8tm7550n58vgzxw9l7yq0zk00000gn/T/tmpZbl5PS/lib/python2.7/site-packages/boto3/resources/factory.py", line 474, in create_resource
    client=self.meta.client)(*args, **kwargs)
  File "/private/var/folders/_0/8tm7550n58vgzxw9l7yq0zk00000gn/T/tmpZbl5PS/lib/python2.7/site-packages/boto3/resources/base.py", line 119, in __init__
    'Required parameter {0} not set'.format(identifier))
ValueError: Required parameter name not set

==============

Need help? Found a bug? Let us know! :D
File bug reports on GitHub here: https://github.com/Miserlou/Zappa
And join our Slack channel here: https://slack.zappa.io
Love!,
 ~ Team Zappa!

**Comment by maebert** [comment] 2017-01-06 20:53
Can't reproduce that - could you send me a copy of your `flinkhose_config.yaml`?

**Comment by liquidweavergit** [comment] 2017-01-06 22:28
components:
  DataCollector:
    app_function: data_collector.collect
    type: LambdaComponent
  Druid:
    type: EC2Component
  EMR:
    job: flinkjob.jar
    schema: EMR.json
    service_role: DataPipelineDefaultRole
    subnet: subnet-0cee147a
    type: EMRComponent
  Firehose:
    schema: Firehose.json
    type: FirehoseComponent
  Heartbeat:
    app_function: heartbeat_app.beat
    events:
    - expression: rate(6 hours)
      function: heartbeat_app.beat
    schema: EMR.json
    type: LambdaComponent
  IndexTable:
    schema: IndexDB.json
    type: DynamoDBComponent
  Indexer:
    app_function: indexer_app.index
    events:
    - event_source:
        arn: arn:aws:s3:::test-one-data
        events:
        - s3:ObjectCreated:*
      function: indexer_app.index
    type: LambdaComponent
data_bucket: test-one-data
project_name: test-one
role_name: test-one-execution-role
stream_name: test-one-stream
table_name: test-one-metadata
upload_bucket: test-one-uploads

**Comment by KingOfPoptart** [comment] 2017-01-12 00:10
@liquidweavergit - please pull the latest and retest, should be fixed

**Closed** 2017-01-12 00:10 UTC
Labels: bug
